--- #YAML:1.0
name:                Tie-Hash-ImmutableKeys
version:             1.11
abstract:            Perl module to create a HASH where keys are immutable but not the leaf data.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - root <root@>
